# Generated by Django 4.2.16 on 2024-11-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrappedapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
