# Generated by Django 4.2.15 on 2024-12-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrappedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeninghistory',
            name='album_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='artist_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='track_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='access_token',
            field=models.CharField(help_text='The access token for Spotify API requests.', max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='display_name',
            field=models.CharField(blank=True, help_text='Spotify display name of the linked account.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='refresh_token',
            field=models.CharField(help_text='The refresh token for renewing the access token.', max_length=512),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='The unique Spotify ID for the account.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='artist_thank_you',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='personality',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='personality_word',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='sound_town',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='spotifywrapped',
            name='title',
            field=models.CharField(default='My Spotify Wrapped', max_length=512),
        ),
    ]
