# Generated by Django 4.2.16 on 2024-11-25 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Wrappedapp', '0002_spotifyaccount_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyaccount',
            name='profile_image',
            field=models.URLField(blank=True, help_text="URL to the user's Spotify profile image.", null=True),
        ),
        migrations.AddField(
            model_name='spotifyaccount',
            name='profile_url',
            field=models.URLField(blank=True, help_text="URL to the user's Spotify profile.", null=True),
        ),
        migrations.AddField(
            model_name='spotifyaccount',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='The unique Spotify ID for the account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='access_token',
            field=models.CharField(help_text='The access token for Spotify API requests.', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='display_name',
            field=models.CharField(blank=True, help_text='Spotify display name of the linked account.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='expires_at',
            field=models.DateTimeField(help_text='The expiration time of the current access token.'),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='refresh_token',
            field=models.CharField(help_text='The refresh token for renewing the access token.', max_length=255),
        ),
        migrations.AlterField(
            model_name='spotifyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WrappedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='The year this summary covers.')),
                ('top_tracks', models.JSONField(help_text="JSON representation of the user's top tracks.")),
                ('top_artists', models.JSONField(help_text="JSON representation of the user's top artists.")),
                ('top_genres', models.JSONField(help_text="JSON representation of the user's top genres.")),
                ('listening_minutes', models.IntegerField(help_text='Total minutes listened during the year.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrapped_summaries', to='Wrappedapp.spotifyaccount')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('played_at', models.DateTimeField()),
                ('duration_ms', models.IntegerField(help_text='Duration of the track in milliseconds.')),
                ('spotify_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='Wrappedapp.spotifyaccount')),
            ],
        ),
    ]
