# Generated by Django 4.2.16 on 2024-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrappedapp', '0003_spotifyaccount_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
