# Generated by Django 5.1.2 on 2024-11-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wrappedapp", "0005_spotifywrapped"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywrapped",
            name="artist_thank_you",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="sound_town",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="spotifywrapped",
            name="top_podcasts",
            field=models.JSONField(default=dict),
        ),
    ]
