# Generated by Django 5.1.2 on 2024-11-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wrappedapp", "0006_spotifywrapped_artist_thank_you_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifywrapped",
            name="personality_word",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
