# Generated by Django 5.1.2 on 2024-11-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Wrappedapp", "0007_spotifywrapped_personality_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifywrapped",
            name="top_songs",
            field=models.JSONField(default=list),
        ),
    ]
