# Generated by Django 5.1.2 on 2024-11-28 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Wrappedapp", "0009_spotifytoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpotifyToken",
        ),
    ]
