name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Print environment variable checks (debugging)
      run: |
        echo "Checking if SECRET_KEY is set: ${#SECRET_KEY}"
        echo "Checking if SPOTIFY_CLIENT_ID is set: ${#SPOTIFY_CLIENT_ID}"
        echo "Checking if SPOTIFY_CLIENT_SECRET is set: ${#SPOTIFY_CLIENT_SECRET}"
        echo "Checking if SPOTIFY_REDIRECT_URI is set: ${#SPOTIFY_REDIRECT_URI}"
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest coverage

    - name: Lint with pylint
      run: |
        pylint Wrappedapp/ --exit-zero  # This will prevent the workflow from failing based on the score alone

    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
      run: |
        pytest --cov=Wrappedapp Wrappedapp/tests.py  # Pointing directly to tests.py
  
    - name: Check code coverage
      run: |
        coverage run -m pytest Wrappedapp/tests/
        coverage report --fail-under=80  # Enforce 80% coverage threshold
